apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: application
  namespace: fleet-default
spec:
  branch: master
  insecureSkipTLSVerify: false
  paths: 
  - "/fleet/application"
  - "/fleet/helm-example"
  repo: https://github.com/shpwrck/RAHS
  targets:
  - clusterSelector:
      matchLabels:
        role: primary
    name: primary
  - clusterSelector:
      matchLabels:
        role: standby
    name: standby
type: fleet.cattle.io.gitrepo

